AWSTemplateFormatVersion: '2010-09-09'
Description: Testing deployment of a nested stack with gitsync

Parameters:
  CfnBucketUrl:
    Type: String
    Description: S3 Bucket in which your nested templates can be found

Resources:
  NestedStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub '${CfnBucketUrl}/child.yml'
      Parameters:
        RoleName: 'MyNestedRole'

